### ISSUE TITLE
Add upsells for the plus plugin

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/azera-shop#102]
In Frontpage sections, add this messages like in llorix one http://prntscr.com/dn2fd0  http://prntscr.com/dn2gjz, but make sure you use sprintf for the string, not how it is now in llorix

The PLUS plugin is https://themeisle.com/plugins/azera-shop-plus/

At the bottom of customize, add View PRO version -> Get it.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu I think because you used 'Check out the %sPRO version%s' , and not used %1$s and %2$s, it looks like this http://prnt.sc/dqlxdk . Even though it would work like that too, it seems it's ok to always have the parameters ordered like %1$s, %2$s, %3$s etc

Also, please add this too http://prnt.sc/dn2gjz in Colors

**Comment by cristian-ungureanu** [comment]
@rodica-andronache done!
