### ISSUE TITLE
The "loading circle" won't stop loading…

### ISSUE THREAD

**Issue by verum8** [Codeinwp/azera-shop#108]
After setting up Our services sector (with Azera shop plugin) does not load page - The "loading circle" still loading… After disabling the plugin site is functioning normally. Why? Where is the problem?

**Comment by rodica-andronache** [comment]
Hi @verum8 ,

Thank you for contacting us.
Can you please give me more details about the issue? I tested on my side, and couldn't replicate it.
Can you also pass me your site URL so I can see the issue?

Thank you,
Rodica

**Comment by verum8** [comment]
Hi @rodica-andronache .

When I installed the Azera Shop template, it was ok. Then I update the template to actual version. It was ok, but template want to install plugin Azera Shop Companinion. It was ok. I change header picture and text, ok. So I started to edit. Ok. I think the problem came meanwhile I was edited section Our Services - then the page has not displayed. Only loading circle. Page is www.nevi.8u.cz

Thank you for your help and sorry for my english...

**Comment by rodica-andronache** [comment]
Hi @verum8 ,

From what I see, I think the only thing that can cause this, may be the data entered in the Our Services section. 

To make things easier and quicker, would you mind installing our dedicated support plugin? It will help us debug the issue more effectively:               

http://bit.ly/themeisle-pirate-parrot

Please see this document on how to install plugins manually if you need help: http://docs.themeisle.com/article/199-how-to-install-wordpress-plugins


After you install the plugin, please go to your WordPress dashboard, then to "Tools" and "ThemeIsle Support Parrot".

Once there, just click on "Call Parrot". The plugin will generate a support token. Please copy-paste it and send it to me here.

Thank you,
Rodica

**Comment by verum8** [comment]
@rodica-andronache token is 3@R2%6$umA(b7XnzD

Thanks.

**Comment by rodica-andronache** [comment]
Hi @verum8 ,

I couldn't access your site, but I think most likely this is caused by the text entered in the Services section. If you are still able to access the customizer, could you please try and delete the content in the Services section and try to see if this makes everything ok? If that is the case, also let me know what the text was, so I can try it myself, and see what we can do from the theme.

Thank you,
Rodica

**Comment by verum8** [comment]
Hello @rodica-andronache
you are right. The problem is the main title. When it is empty - there is the problem.
Is there any possibility for repair it?

Thank you.

**Comment by rodica-andronache** [comment]
Hi @verum8 ,

It seems there was an issue in the Azera Shop Companion plugin causing this issue and we just released an update to fix it.
Can you please update and let me know if everything is ok?

Thank you,
Rodica

**Comment by verum8** [comment]
@rodica-andronache 
Yes, it is ok now. Thank you so much!

**Comment by rodica-andronache** [comment]
Hi @verum8 ,

I'm really glad to hear everything is ok now.
If you are happy with the theme or our support, you can always leave us a review here https://wordpress.org/support/theme/azera-shop/reviews/#new-post . It would help us a lot.

Regards,
Rodica
