### ISSUE TITLE
Team section, background image

### ISSUE THREAD

**Issue by cheuf** [Codeinwp/azera-shop#111]
When I changed the background image of the team section, I noticed that the image was repeated. So I checked the source code and saw that the image was added in the "style" attribute of the section with the CSS "background" property.
This will remove the following CSS properties:
.team {
    Background-color: #FFF;
    Border-bottom: 1px solid #eaebec;
    Background-position: 50% 50%;
    Background-repeat: no-repeat;
    Background-attachment: fixed;
    Background-size: cover;
}

It is therefore necessary to put "background-image" and not "background" so as not to lose these properties CSS.

**Comment by rodica-andronache** [comment]
Hi @cheuf ,

Thank you very much for contacting us and for letting us know about this issue. You are right about the solution.
We'll have this fix in the next update of the Azera Shop Companion plugin, where the code for this section is located.

Thank you and have a nice day ,

Rodica
