### ISSUE TITLE
No shop sidebar

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/azera-shop#119]
@rodica-andronache I think a shop sidebar is a basic need for all WooCommerce optimized themes, I couldn't find one for Azera Shop could we add one? cc @ineagu

**Comment by UVLabs** [comment]
+1

**Comment by UVLabs** [comment]
+1

**Comment by poonam279** [comment]
+1

**Comment by UVLabs** [comment]
+1

**Comment by rodica-andronache** [comment]
Add a sidebar called Shop Sidebar, which will only appear on the shop page (not on single, cart, checkout etc ).

**Comment by poonam279** [comment]
+1
