### ISSUE TITLE
Traslate

### ISSUE THREAD

**Issue by amdh110** [Codeinwp/azera-shop#132]
Hello every one
I'm a beginner and I want to translate this theme to my language. how can I do it with "azera-shop.pot". please explain.
thanks

**Comment by rodica-andronache** [comment]
Hi @amdh110 ,

Thank you for contacting us. We are really happy you want to contribute to our theme.
The easiest way to translate the theme would be to do it here https://translate.wordpress.org/projects/wp-themes/azera-shop . You just need to create an account if you don't have one already , select your language, and add the translation for each string. After that, and admin will review your contribution and mark them as approved.
Please let me know if I can help you with anything else. 

Regards,
Rodica
