### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/azera-shop#133]
@cristian-ungureanu I found a few issues here 
- http://prnt.sc/exusbm the decoding is duplicated
- http://prnt.sc/exuoaj notification in shortcodes section when no shortcode is entered
- the default values for the Contact info sections have some weird spaces, making the removal of the content difficult. http://prnt.sc/exvrgy - this happens also for the companion, in some sections

**Comment by rodica-andronache** [comment]
and this layout is broken in customizer http://prntscr.com/exvy2f

**Comment by cristian-ungureanu** [comment]
fixed here https://github.com/Codeinwp/azera-shop/pull/134 , sorry, forgot to make separate branch
