### ISSUE TITLE
Hoaver Issue on Team Section

### ISSUE THREAD

**Issue by Dutchman1990** [Codeinwp/azera-shop#139]
![capture](https://user-images.githubusercontent.com/15785457/26917788-34ca9e1c-4c4d-11e7-822f-ee64e78800a0.PNG)
Issue With Hoaver effect.

**Comment by rodica-andronache** [comment]
Hi @Dutchman1990 ,

Can you please give me your site URL so I can see the issue? I think it might be a conflict with a plugin.

Regards,
Rodica
