### ISSUE TITLE
Search Input Shows Weird Symbols

### ISSUE THREAD

**Issue by johndoegithub** [Codeinwp/azera-shop#147]
![screen shot 2017-10-30 at 11 47 55](https://user-images.githubusercontent.com/4338436/32174172-4fbd061a-bd68-11e7-8b64-659a146678e2.png)

The desing of this theme is amazing, and I am pretty sure that the way the search fied shows up when you click is not what the designers intended.

**Comment by rodica-andronache** [comment]
Hi @johndoegithub,

Yes, that's a small bug, it's not how we want the search icon to look like. Thanks for reporting this. We'll fix it as soon as possible.

Regards,
Rodica

**Comment by johndoegithub** [comment]
Thank you :)
