### ISSUE TITLE
Recommend our Adblock Notify plugin in the "About theme" page

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/azera-shop#25]

**Comment by rodica-andronache** [comment]
@claudiuvertistudio scuze daca ti-am spus gresit sau nu am fost clara. Aici trebuie tot ca la zerif lite, recomandate in pagina de About Azera. Nu cu tgm

**Comment by claudiuvertistudio** [comment]
@rodica-andronache  cand am facut commit am uitat sa pun si id-ul issue-ului. 
aici e link-ul la commit: https://github.com/Codeinwp/azera-shop/commit/3167abe3a201caa6098f4df60e6fac12a2e393ca
