### ISSUE TITLE
Recommend our Feedzy plugin in the "About theme" page

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/azera-shop#26]

**Comment by rodica-andronache** [comment]
@claudiuvertistudio tot asa, aici ar trebui in pagina de About Azera, nu cu tgm

**Comment by claudiuvertistudio** [comment]
@rodica-andronache  cand am facut commit am uitat sa pun si id-ul issue-ului. 
aici e link-ul la commit: https://github.com/Codeinwp/azera-shop/commit/3167abe3a201caa6098f4df60e6fac12a2e393ca
