### ISSUE TITLE
Change header image and text

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/azera-shop#30]
http://prntscr.com/aow41r

Like here: http://templateocean.com/stamp/image-bg/2-home-style-two/index.html

font , image, spacing, lighter image

**Comment by rodica-andronache** [comment]
imaginea pentru header asta: https://static.pexels.com/photos/7409/pexels-photo.jpg

**Comment by rodica-andronache** [comment]
http://prntscr.com/aoweyy

**Comment by abaicus** [comment]
Am schimbat în ultimul pull request
