### ISSUE TITLE
Remove Demo Content

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/azera-shop#33]
The demo content from template-frontpage.php should either be removed or replaced with existing content from the user's site.
The social media links should not link to # by default. Either disable them or show the user's existing links.

**Comment by ineagu** [comment]
Uite cum as zice sa facem aici : 

1. Main line header - punem site title as default
2. 2nd line - punem site tagline as default
3. header background image, lasam imaginea noastra
4. Logos lasam logo-urile astea ( dar punem sa fie afisate doar daca user_can_edit_themeoptions )
5. Ribbon ( scriem ceva de genul : In order to edit the text here you should go to customizer, iar pe buton sa scrie gen : Edit This ), care duce in customizer, again, afisam asta only if user_can_edit 
6.In footer la social icons afisam default in loc de # site_url 

Also what if we add a widget area before the shop section ? it will affect the generic_plugin ?

**Comment by cristian-ungureanu** [comment]
@ineagu ,la our story banuiesc ca facem ca la ribbon, nu?

**Comment by ineagu** [comment]
our story o sa fie scos de tot, parca era la andrei task-ul, daca nu a
facut poti face tu

On Fri, Apr 8, 2016 at 5:13 PM, cristian-ungureanu <notifications@github.com
> wrote:

> @ineagu <https://github.com/ineagu> ,la our story banuiesc ca facem ca la
> ribbon, nu?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/azera-shop/issues/33#issuecomment-207447342>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
