### ISSUE TITLE
MIssing translations

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/azera-shop#35]
This code from welcome-screen.php has text that is not internationalized:
add_theme_page( 'About Azera Shop', 'About Azera Shop', 'activate_plugins', 'azera-shop-welcome', array( $this, 'azera_shop_welcome_screen' ) );

This text in getting-started.php:

<h1 class="azera-shop-welcome-title">Welcome to Azera Shop! <?php if( !empty($azera_shop['Version']) ): ?> <sup id="azera-shop-theme-version"><?php echo esc_attr( $azera_shop['Version'] ); ?> </sup><?php endif; ?></h1>

I WOULD MENTION THAT WE SHOULD NOT TRANSLATE THE THEME NAME, just About, or WELCOME TO

**Comment by rodica-andronache** [comment]
@cristian-ungureanu $theme_name should be a variable with the azera_shop prefix. 
Also, here http://prntscr.com/aqtcav you should display the version number using wp_get_theme() Right now, it's using a non existing variable.
