### ISSUE TITLE
Redo demo content

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/azera-shop#51]

**Comment by ineagu** [comment]
I think we can start by removing all content and importing all content from ParallaxOne.

**Comment by ineagu** [comment]
so we would have the top menu, blog posts, content, siteorigin pages etc and after that we can see how we can work out the products images.

**Comment by mileamadalin** [comment]
@rodica-andronache Done! O poti verifica si vedea daca totul este ok. :D

**Comment by ineagu** [comment]
de ce vad doar o poza pe home la shop ? ?



On Tue, May 17, 2016 at 5:09 PM, Madalin Milea <notifications@github.com>
wrote:

> @rodica-andronache <https://github.com/rodica-andronache> Done! O poti
> verifica si vedea daca totul este ok. :D
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/azera-shop/issues/51#issuecomment-219748650>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by mileamadalin** [comment]
Acum trebuie sa fie ok, schimbam eu categoriile.

**Comment by rodica-andronache** [comment]
@mileamadalin paginile cu siteorigin nu arata ok http://prnt.sc/b55ohz cred ca trebuie sa le mai iei la mana

**Comment by mileamadalin** [comment]
Ciudat. Ma voi uita, merci

**Comment by mileamadalin** [comment]
@rodica-andronache Done!

**Comment by rodica-andronache** [comment]
@mileamadalin mersi :) Ar mai fi trebuit activat si pluginul Shortcodes Ultimate, pt ca erau folosite shortcode-uri de la el.
http://prntscr.com/bbr65q
L-am activat eu acum.
