### ISSUE TITLE
IDs for Shortcode Section

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/azera-shop#62]
Shortcode section needs to have IDs, just like Parallax One Plus.

**Comment by rodica-andronache** [comment]
@abaicus I just realised that it's not ok to add the id like that, because the user can add multiple shortcodes, and each has to have different id's. You can check how parallax one plus works and if it's ok, you can replicate it here :)

**Comment by abaicus** [comment]
@rodica-andronache Hope it's right now. Sorry for the confusion. :+1:

**Comment by rodica-andronache** [comment]
@abaicus you commited on production here :D it's not a big issue, just wanted to let you know
