### ISSUE TITLE
Display featured items on front-page

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/azera-shop#64]
The theme comes with an option to display categories on the front-page but WooCommerce has a Featured items list so maybe we can give an option to include that.

It was suggested by a customer, who is probably reading this message right now. In which case, Hi WILL! :)

@ineagu @rodica-andronache Your thoughts?

**Comment by rodica-andronache** [comment]
@HardeepAsrani you are talking about this http://www.modernmarketingpartners.com/set-featured-products-woocommerce/ ?

To add an option here:
http://prntscr.com/brxjop ?

**Comment by ineagu** [comment]
is a good idea, but not a priority at the moment.

On Tue, Jul 12, 2016 at 2:39 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @HardeepAsrani <https://github.com/HardeepAsrani> you are talking about
> this
> http://www.modernmarketingpartners.com/set-featured-products-woocommerce/
> ?
>
> To add an option here:
> http://prntscr.com/brxjop ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/azera-shop/issues/64#issuecomment-232034753>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DJOAO2VllLXzkkfUckPRZGT56Cjhks5qU4rwgaJpZM4I-aM_>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
