### ISSUE TITLE
frontpage displays faulty

### ISSUE THREAD

**Issue by alexandrastann** [Codeinwp/azera-shop#65]
when you try to disable all the section from deleting the content and only let the shop section active, without title, and activate the Parallax effect, images from the shop overlay with the big title section
![azera issue](https://cloud.githubusercontent.com/assets/12390772/16760401/3de3cc90-4824-11e6-9928-fd5138e36145.jpg)

**Comment by cristianraiber** [comment]
### This also seems to happen when you have all sections enabled & parallax effect turned on. 
![screen shot 2016-08-08 at 12 04 54](https://cloud.githubusercontent.com/assets/7841556/17474759/578666fc-5d60-11e6-9aa3-9d345c80d844.png)
