### ISSUE TITLE
Section Frontpage settings purpose?

### ISSUE THREAD

**Issue by cristianraiber** [Codeinwp/azera-shop#68]
What's the purpose of this section? It feels like a placeholder for some text + a link. Link doesn't open in new tab and also goes to llorix one documentation. Just thought I'd let you guys know :)

**Comment by rodica-andronache** [comment]
@cristianraiber that section is used to inform users how they can achive the frontpage look like on the demo. I know the link goes to a doc for llorix one, but that is because the content of the doc is the same :)

**Comment by cristianraiber** [comment]
@rodica-andronache - awesome! thx.
