### ISSUE TITLE
Section Frontpage sections -> Logo bars section typo?

### ISSUE THREAD

**Issue by cristianraiber** [Codeinwp/azera-shop#69]
'**Add new social icon**' doesn't seem like the proper label for this ... 

![screen shot 2016-08-08 at 12 08 21](https://cloud.githubusercontent.com/assets/7841556/17474877/db978da4-5d60-11e6-97da-ad79370e08ad.png)

**Comment by rodica-andronache** [comment]
@cristianraiber you are right, maybe this is not the best text, but we can't afford to lose translations here https://translate.wordpress.org/projects/wp-themes/azera-shop, so we need to close this.

**Comment by ineagu** [comment]
we can keep it open.
