### ISSUE TITLE
Cart button

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/azera-shop#7]
@ineagu should we add the cart button in the menu, like on shop isle?

**Comment by ineagu** [comment]
yes, we can

On Thu, Feb 11, 2016 at 11:35 AM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> should we add the cart button in the
> menu, like on shop isle?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/azera-shop/issues/7>.
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
