### ISSUE TITLE
Map shortcode control still visible, plugin disabled

### ISSUE THREAD

**Issue by cristianraiber** [Codeinwp/azera-shop#70]
Control displays although Intergeo Google Maps is disabled ... Wouldn't it be a better UX to just show a text notice when the plugin is disabled and ask users to install/enable it? 

![screen shot 2016-08-08 at 12 13 58](https://cloud.githubusercontent.com/assets/7841556/17475023/9aa4fc9a-5d61-11e6-8ab6-13e0a3f7edb7.png)

**Comment by rodica-andronache** [comment]
@cristianraiber not sure if we should do this, as the section works with other shortcodes from other plugins. We just recommend Intergeo Maps, because it's our plugin :)
