### ISSUE TITLE
Page content for frontpage template isn't being displayed

### ISSUE THREAD

**Issue by cristianraiber** [Codeinwp/azera-shop#71]
As the title says ... go enter some content in Pages -> Frontpage (template: frontpage) and it doesn't display anywhere ... @rodica-andronache

**Comment by rodica-andronache** [comment]
@cristianraiber I don't understand what you mean here

**Comment by cristianraiber** [comment]
@rodica-andronache - Go to Pages. Locate the page using the template: 'Frontpage'. Enter some content in the visual editor. Click on save. Locate the entered content in the front-end view of the site :)

**Comment by rodica-andronache** [comment]
Ok, I understand now :) We'll see if we add this. @ineagu what do you think?

**Comment by ineagu** [comment]
Is not really ok, however we can ignore it for now
