### ISSUE TITLE
Content wrap, on contact page (with contact page template selected) has a min-height

### ISSUE THREAD

**Issue by cristianraiber** [Codeinwp/azera-shop#72]
See attached screenshot for problem. (it's all that white space). This happens on a resolution of 1440p or 2560 x 1440. 

---

![screen shot 2016-08-19 at 19 32 36](https://cloud.githubusercontent.com/assets/7841556/17816823/d821545c-6643-11e6-8a99-125d5747da96.png)

**Comment by claudiuvertistudio** [comment]
this is not a problem, because if a page has no content then the footer should be fixed at the bottom of the page

**Comment by cristianraiber** [comment]
@claudiuvertistudio - look between map & footer of the site. That's the whitespace I'm talking about.

**Comment by rodica-andronache** [comment]
@cristianraiber yeah, that space is because we have a js that sticks the footer at the bottom of the page. Don't think it's a problem
