### ISSUE TITLE
[Azera Shop Plus] Themeisle page images

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/azera-shop#97]
We need images for the ti page for the Plus version of Azera Shop https://themeisle.com/plugins/azera-shop-plus/.

Similar to https://themeisle.com/plugins/parallax-one-plus/ and https://themeisle.com/plugins/llorix-one-plus/

**Comment by claudiuvertistudio** [comment]
[azer-plus.zip](https://github.com/Codeinwp/azera-shop/files/675736/azer-plus.zip)

**Comment by rodica-andronache** [comment]
@abaicus this is the final version for the ti page https://themeisle.com/plugins/azera-shop-plus/ . Can you please check it? It's good to be published? :D
